name: Go
on: [push]
env:
# DOCKER_REG: docker.pkg.github.com
  DOCKER_REG: docker.io
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

#   - name: Build Docker Image and Push @ Github-Registry
#     run: |
#       REPO=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`
#       REF=`echo ${{github.ref}} | awk -F/ '{print $NF}'`

#       CONTAINER_IMAGE=$DOCKER_REG/$REPO/img:${{ github.sha }}
#       CONTAINER_IMAGE_ALIAS=$DOCKER_REG/$REPO/img:$REF

#       echo '${{ secrets.GITHUB_TOKEN }}' | docker login --username=${{ github.actor }} $DOCKER_REG --password-stdin

#       docker build . -t $CONTAINER_IMAGE
#       docker push $CONTAINER_IMAGE
#       docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE_ALIAS
#       docker push $CONTAINER_IMAGE_ALIAS

    - name: Build Docker Image and Push @ Dockerhub
      run: |
        REPO="hydroprotocolio/ethereum-watcher"
        REF=`echo ${{github.ref}} | awk -F/ '{print $NF}'`

        CONTAINER_IMAGE=$DOCKER_REG/$REPO:${{ github.sha }}
        CONTAINER_IMAGE_ALIAS=$DOCKER_REG/$REPO:$REF

        echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login --username=${{ secrets.DOCKERHUB_USERNAME }} $DOCKER_REG --password-stdin

        docker build . -t $CONTAINER_IMAGE
        docker push $CONTAINER_IMAGE
        docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE_ALIAS
        docker push $CONTAINER_IMAGE_ALIAS
